### ISSUE TITLE
(Manjaro) Login failed

### ISSUE THREAD

**Issue by TinMan1325** [GoBig87/NordVpnLinuxGUI#10]
I keep getting a Login failed message when I click the Login button
![Screenshot from 2022-07-09 21-08-44](https://user-images.githubusercontent.com/68861896/178127590-b7fff3b2-219a-4562-84a9-5551b23ccf7e.png)

And also an error when changing any of the settings
![Screenshot from 2022-07-09 21-15-29](https://user-images.githubusercontent.com/68861896/178127647-33f6e4c7-7cdb-4d9d-b9e7-1ad9dc6ece75.png)

https://gist.github.com/TinMan1325/e24c775bd55be20a3f5a796277c09686

**Comment by GoBig87** [comment]
Can you run it through the terminal?  By finding the NordVpnLinuxGUI.sh file inside the source dir and running with ./NordVpnLinuxGUI.sh?  Once that happens can you copy the log from the terminal and paste it here.  I haven't tested on Manjaro.

**Comment by TinMan1325** [comment]
`$ '/home/tinman1325/NordVpnLinuxGUI/NordVPNLinuxGUI.sh' 
[INFO   ] [Logger      ] Record log in /home/tinman1325/.kivy/logs/kivy_22-07-09_5.txt
[INFO   ] [Kivy        ] v2.1.0
[INFO   ] [Kivy        ] Installed at "/home/tinman1325/NordVpnLinuxGUI/venv/lib/python3.10/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0]
[INFO   ] [Python      ] Interpreter at "/home/tinman1325/NordVpnLinuxGUI/venv/bin/python"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 189 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [KivyMD      ] 0.104.2, git-bc7d1f5, 2021-06-06 (installed at "/home/tinman1325/NordVpnLinuxGUI/venv/lib/python3.10/site-packages/kivymd/__init__.py")
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 515.57'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[WARNING] [Factory     ] Ignored class "DialogContainer" re-declaration. Current -  module: None, cls: None, baseclass: MDCard+FakeRectangularElevationBehavior, filename: None. Ignored -  module: None, cls: None, baseclass: MDCard+FakeRectangularElevationBehavior, filename: None.
[INFO   ] [GL          ] NPOT texture support is available
Sending Command: nordvpn countries
Error: /bin/sh: line 1: nordvpn: command not found

/bin/sh: line 1: nordvpn: command not found

Sending Command: nordvpn groups
Error: /bin/sh: line 1: nordvpn: command not found

/bin/sh: line 1: nordvpn: command not found

Sending Command: nordvpn settings
Error: /bin/sh: line 1: nordvpn: command not found

/bin/sh: line 1: nordvpn: command not found

Sending Command: nordvpn account
Error: /bin/sh: line 1: nordvpn: command not found

/bin/sh: line 1: nordvpn: command not found

Sending Command: nordvpn status
Error: /bin/sh: line 1: nordvpn: command not found

/bin/sh: line 1: nordvpn: command not found

Sending Command: nordvpn version
Error: /bin/sh: line 1: nordvpn: command not found

/bin/sh: line 1: nordvpn: command not found

[INFO   ] [Clipboard   ] Provider: sdl2(['clipboard_xclip', 'clipboard_xsel', 'clipboard_dbusklipper', 'clipboard_gtk3'] ignored)
[CRITICAL] [Cutbuffer   ] Unable to find any valuable Cutbuffer provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
xclip - FileNotFoundError: [Errno 2] No such file or directory: 'xclip'
  File "/home/tinman1325/NordVpnLinuxGUI/venv/lib/python3.10/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    mod = importlib.__import__(name='{2}.{0}.{1}'.format(
  File "<frozen importlib._bootstrap>", line 1129, in __import__
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/tinman1325/NordVpnLinuxGUI/venv/lib/python3.10/site-packages/kivy/core/clipboard/clipboard_xclip.py", line 17, in <module>
    p = subprocess.Popen(['xclip', '-version'], stdout=subprocess.PIPE,
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

xsel - FileNotFoundError: [Errno 2] No such file or directory: 'xsel'
  File "/home/tinman1325/NordVpnLinuxGUI/venv/lib/python3.10/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    mod = importlib.__import__(name='{2}.{0}.{1}'.format(
  File "<frozen importlib._bootstrap>", line 1129, in __import__
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/tinman1325/NordVpnLinuxGUI/venv/lib/python3.10/site-packages/kivy/core/clipboard/clipboard_xsel.py", line 16, in <module>
    p = subprocess.Popen(['xsel'], stdout=subprocess.PIPE)
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

[INFO   ] [Base        ] Start application main loop
Sending Command: nordvpn login
Error: /bin/sh: line 1: nordvpn: command not found

Checking account....
not logged in...
Sending Command: nordvpn account
Error: /bin/sh: line 1: nordvpn: command not found
`

**Comment by GoBig87** [comment]
You're missing the nordvpn cli tool.  Can you try installing with it with
`sh <(curl -sSf https://downloads.nordcdn.com/apps/linux/install.sh)`

**Comment by TinMan1325** [comment]
> You're missing the nordvpn cli tool. Can you try installing with it with `sh <(curl -sSf https://downloads.nordcdn.com/apps/linux/install.sh)` in a terminal. The try `nordvpn version`

Do I do it while in the NordVpnLinuxGUI folder?

**Comment by GoBig87** [comment]
You don't have to.  Nord only supplies a vpn terminal client for linux.  I just wrapped a GUI around their command line client.  This just installs the official Nord VPN tools to be used anywhere on your user account.

**Comment by TinMan1325** [comment]
```
$ sh <(curl -sSf https://downloads.nordcdn.com/apps/linux/install.sh)
Error: Couldn't identify the package manager
```

**Comment by GoBig87** [comment]
```
#!/bin/sh

# check for root access
SUDO=
if [ "$(id -u)" -ne 0 ]; then
    SUDO=$(command -v sudo 2> /dev/null)

    if [ ! -x "$SUDO" ]; then
        echo "Error: Run this script as root"
        exit 1
    fi
fi

set -e
ARCH=$(uname -m)
BASE_URL=https://repo.nordvpn.com/
KEY_PATH=/gpg/nordvpn_public.asc
REPO_PATH_DEB=/deb/nordvpn/debian
REPO_PATH_RPM=/yum/nordvpn/centos
RELEASE="stable main"
ASSUME_YES=false

# Parse command line arguments. Available arguments are:
# -n                Non-interactive mode. With this flag present, 'assume yes' or 
#                   'non-interactive' flags will be passed when installing packages.
# -b <url>          The base URL of the public key and repository locations.
# -k <path>         Path to the public key for the repository.
# -d <path|file>    Repository location for debian packages.
# -v <version>      Debian package version to use.
# -r <path|file>    Repository location for rpm packages.
while getopts 'nb:k:d:r:v:' opt
do
    case $opt in
        n) ASSUME_YES=true ;;
        b) BASE_URL=$OPTARG ;;
        k) KEY_PATH=$OPTARG ;;
        d) REPO_PATH_DEB=$OPTARG ;;
        r) REPO_PATH_RPM=$OPTARG ;;
        v) RELEASE=$OPTARG ;;
        *) ;;
    esac
done

# Construct the paths to the package repository and its key
PUB_KEY=${BASE_URL}${KEY_PATH}
REPO_URL_DEB=${BASE_URL}${REPO_PATH_DEB}
REPO_URL_RPM=${BASE_URL}${REPO_PATH_RPM}

check_cmd() {
    command -v "$1" 2> /dev/null
}

get_install_opts_for_apt() {
    flags=$(get_install_opts_for "apt")
    RETVAL="$flags"
}

get_install_opts_for_yum() {
    flags=$(get_install_opts_for "yum")
    RETVAL="$flags"
}

get_install_opts_for_dnf() {
    flags=$(get_install_opts_for "dnf")
    RETVAL="$flags"
}

get_install_opts_for_zypper() {
    flags=$(get_install_opts_for "zypper")
    RETVAL="$flags"
}

get_install_opts_for() {
    if $ASSUME_YES; then
        case "$1" in
            zypper)
                echo " -n";;
            *)
                echo " -y";;
        esac
    fi
    echo ""
}

# For any of the following distributions, these steps are performed:
# 1. Add the NordVPN repository key
# 2. Add the NordVPN repository
# 3. Install NordVPN

# Install NordVPN for Debian, Ubuntu, Elementary OS, and Linux Mint
# (with the apt-get package manager)
install_apt() {
    if check_cmd apt-get; then
        get_install_opts_for_apt
        install_opts="$RETVAL"
        # Ensure apt is set up to work with https sources
        $SUDO apt-get $install_opts update
        $SUDO apt-get $install_opts install apt-transport-https

        # Add the repository key with either wget or curl
        if check_cmd wget; then
            wget -qO - "${PUB_KEY}" | $SUDO tee /etc/apt/trusted.gpg.d/nordvpn_public.asc > /dev/null
        elif check_cmd curl; then
            curl -s "${PUB_KEY}" | $SUDO tee /etc/apt/trusted.gpg.d/nordvpn_public.asc > /dev/null
        else
            echo "Couldn't find wget or curl - one of them is needed to proceed with the installation"
            exit 1
        fi

        echo "deb ${REPO_URL_DEB} ${RELEASE}" | $SUDO tee /etc/apt/sources.list.d/nordvpn.list
        $SUDO apt-get $install_opts update
        $SUDO apt-get $install_opts install nordvpn
        exit
    fi
}

# Install NordVPN for RHEL and CentOS
# (with the yum package manager)
install_yum() {
    if check_cmd yum && check_cmd yum-config-manager; then
        get_install_opts_for_yum
        install_opts="$RETVAL"

        repo="${REPO_URL_RPM}"
        if [ ! -f "${REPO_URL_RPM}" ]; then
            repo="${repo}/${ARCH}"
        fi

        $SUDO rpm -v --import "${PUB_KEY}"
        $SUDO yum-config-manager --add-repo "${repo}"
        $SUDO yum $install_opts install nordvpn
        exit
    fi
}

# Install NordVPN for Fedora and QubesOS
# (with the dnf package manager)
install_dnf() {
    if check_cmd dnf; then
        get_install_opts_for_dnf
        install_opts="$RETVAL"
        
        repo="${REPO_URL_RPM}"
        if [ ! -f "${REPO_URL_RPM}" ]; then
            repo="${repo}/${ARCH}"
        fi

        $SUDO rpm -v --import "${PUB_KEY}"
        $SUDO dnf config-manager --add-repo "${repo}"
        $SUDO dnf $install_opts install nordvpn
        exit
    fi
}

# Install NordVPN for openSUSE
# (with the zypper package manager)
install_zypper() {
    if check_cmd zypper; then
        if ! check_cmd curl; then
            echo "Curl is needed to proceed with the installation"
            exit 1
        fi
        get_install_opts_for_zypper
        install_opts="$RETVAL"
        
        $SUDO rpm -v --import "${PUB_KEY}"
        if [ -f "${REPO_URL_RPM}" ]; then
            $SUDO zypper addrepo -f "${REPO_URL_RPM}"
        else 
            $SUDO zypper addrepo -g -f "${REPO_URL_RPM}/${ARCH}" nordvpn
        fi
        $SUDO zypper $install_opts install nordvpn
        exit
    fi
}

install_apt
install_yum
install_dnf
install_zypper

# None of the known package managers (apt, yum, dnf, zypper) are available
echo "Error: Couldn't identify the package manager"
exit 1
```
This is the script that nord uses to install their tool.  Let me look it over and see what might be tripping it up on Manjaro

**Comment by GoBig87** [comment]
Maybe try installing following this guide https://archived.forum.manjaro.org/t/howto-nordvpn-usage-installation-updating-and-troubleshooting/71268.  Once you get the Nord cli tool installed the GUI shouldn't care what OS is running as its all in python.

**Comment by GoBig87** [comment]
You only need to go to step 2 btw.  The rest is just verify it is working properly.  Up to you if you want to try it all

**Comment by TinMan1325** [comment]
Dang, got a new error now
```
$ pamac build nordvpn-bin
sudo systemctl enable --now nordvpnd
```


![Screenshot from 2022-07-09 22-29-11](https://user-images.githubusercontent.com/68861896/178128957-1c8c378d-1107-48ca-8cf5-ee55a6696b09.png)

**Comment by GoBig87** [comment]
`sudo usermod -aG nordvpn $USER`
should fix that one

**Comment by TinMan1325** [comment]
Duuuuuuude! Thank you
If you accepted BAT (Basic Attention Token) I would send you a tip

**Comment by GoBig87** [comment]
Don't worry about it.  Glad I could get you up and running!  Just be sure to double check that your IP is being protected with an online IP checker before you do anything.  I haven't tested on Manjaro at all and I'm not sure if there's any extra steps that you need to do to get nord up and running.

**Comment by TinMan1325** [comment]
Sweet. According to https://whatismyipaddress.com/ it's working

**Comment by GoBig87** [comment]
https://github.com/GoBig87/NordVpnLinuxGUI/pull/11 this PR should fix any future install problems on Manjaro
