### ISSUE TITLE
No uninstall.sh option available to uninstall

### ISSUE THREAD

**Issue by JGT93** [GoBig87/NordVpnLinuxGUI#5]

**Comment by JGT93** [comment]
There is no uninstall script available.

**Comment by GoBig87** [comment]
I've added an uninstall script that deletes the user groups, removes nordvpn client and deletes all the nordvpn gui files.

**Comment by GoBig87** [comment]
https://github.com/GoBig87/NordVpnLinuxGUI/commit/ae8269e37a06f48fff47ea62b043e9bf44dcef7f
