### ISSUE TITLE
Meshnet

### ISSUE THREAD

**Issue by TinMan1325** [GoBig87/NordVpnLinuxGUI#9]
Getting a weird message when I open the GUI (it just started a couple of days ago, everything was working fine until them)

I'll include some images to show what I mean

Also, thank you for creating this, it makes the switch from Windows to Linux so much easier
![nnord](https://user-images.githubusercontent.com/68861896/174504993-78a6b110-ff68-4b7f-952a-6578dff1d308.png)
![nnord2](https://user-images.githubusercontent.com/68861896/174505006-656abf6a-0393-40fd-ab10-28cdc01512f5.png)

**Comment by GoBig87** [comment]
I think I should have fixed this issue in release v1.0.4

**Comment by TinMan1325** [comment]
> Can you get the version for of the nord vpn cli you are using with `nordvpn --version` from a terminal session. I've updated to 3.14.1 and I'll try to reproduce it.

I'm using ordVPN Version 3.14.1

**Comment by GoBig87** [comment]
I fixed it in https://github.com/GoBig87/NordVpnLinuxGUI/commit/527f13b45f213e7dbb66503721338addb4aba9a8#diff-4450553591d1fefaf31ad11ebe41512098b3f52dddbf59da9fc0993786f1dd16R344.  If you use master or the latest 1.0.4 release it should be fixed.

**Comment by TinMan1325** [comment]
> I fixed it in [527f13b#diff-4450553591d1fefaf31ad11ebe41512098b3f52dddbf59da9fc0993786f1dd16R344](https://github.com/GoBig87/NordVpnLinuxGUI/commit/527f13b45f213e7dbb66503721338addb4aba9a8#diff-4450553591d1fefaf31ad11ebe41512098b3f52dddbf59da9fc0993786f1dd16R344). If you use master or the latest 1.0.4 release it should be fixed. Let me know if this fixes it for you and I'll close the issue.

I'm not sure how to update it to 1.0.4

**Comment by GoBig87** [comment]
If you downloaded with git use `git checkout v1.0.4` or if you downloaded it via the zip file you can just replace your files with this https://github.com/GoBig87/NordVpnLinuxGUI/releases/tag/v1.0.4

**Comment by TinMan1325** [comment]
> If you downloaded with git use `git checkout v1.0.4` or if you downloaded it via the zip file you can just replace your files with this https://github.com/GoBig87/NordVpnLinuxGUI/releases/tag/v1.0.4

I put this in the terminal `git checkout v1.0.4` and got `fatal: not a git repository (or any of the parent directories): .git`

**Comment by GoBig87** [comment]
`git pull` to update the repo and then it should work

`jasoninbody@Jasons-MacBook-Air NordVpnLinuxGUI % git checkout v1.0.4
M	ui/assets/images/.DS_Store
HEAD is now at 527f13b adding curl install to installer and fixing mesh warning`

**Comment by TinMan1325** [comment]
> `git pull` to update the repo and then it should work
> 
> `jasoninbody@Jasons-MacBook-Air NordVpnLinuxGUI % git checkout v1.0.4 M ui/assets/images/.DS_Store HEAD is now at 527f13b adding curl install to installer and fixing mesh warning`
> 
> You shouldn't have to run the installer. That just updates some dependencies which you already have. The only thing that changed is a python file

I'm still getting the same error. I put `git pull` in the terminal and it says ```
$ git pull
fatal: not a git repository (or any of the parent directories): .git
```

**Comment by GoBig87** [comment]
oh, where is your NordVpnLinuxGUI directory?  You need to be inside of that for git to work.  So cd into the NordVpnLinuxGUI directory.  And this will only work if you used `git clone https://github.com/GoBig87/NordVpnLinuxGUI.git` (or equivalent ssh url).  If you downloaded it as a zip or as a tar.gz it won't have the .git files for git to update

**Comment by TinMan1325** [comment]
> oh, where is your NordVpnLinuxGUI directory? You need to be inside of that for git to work. So cd into the NordVpnLinuxGUI directory. And this will only work if you used `git clone https://github.com/GoBig87/NordVpnLinuxGUI.git` (or equivalent ssh url). If you downloaded it as a zip or as a tar.gz it won't have the .git files for git to update

```
~/NordVpnLinuxGUI$ git clone https://github.com/GoBig87/NordVpnLinuxGUI.git
Cloning into 'NordVpnLinuxGUI'...
remote: Enumerating objects: 492, done.
remote: Counting objects: 100% (492/492), done.
remote: Compressing objects: 100% (400/400), done.
remote: Total 492 (delta 127), reused 423 (delta 70), pack-reused 0
Receiving objects: 100% (492/492), 772.62 KiB | 4.74 MiB/s, done.
Resolving deltas: 100% (127/127), done.
```
I still get the same Meshnet message when I open it

**Comment by GoBig87** [comment]
So when you did 
`~/NordVpnLinuxGUI$ git clone https://github.com/GoBig87/NordVpnLinuxGUI.git`
You made another copy inside the ~/NordVpnLinuxGUI directory.  So now you have 
~/NordVpnLinuxGUI (that contains your original files) and ~/NordVpnLinuxGUI/NordVpnLinuxGUI a new directory that you cloned from git hub.  You can fix this with `mv NordVpnLinuxGUI .` this will move all files from what you just cloned into your original NordVpnLinuxGUI directory.

**Comment by TinMan1325** [comment]
```
~/NordVpnLinuxGUI$ mv NordVpnLinuxGUI
mv: missing destination file operand after 'NordVpnLinuxGUI'
Try 'mv --help' for more information.
```

**Comment by GoBig87** [comment]
what does `git branch` say?

**Comment by TinMan1325** [comment]
```
~/NordVpnLinuxGUI$ git branch
* main

```

**Comment by GoBig87** [comment]
and `git checkout v1.0.4` fails?

**Comment by TinMan1325** [comment]
```
~/NordVpnLinuxGUI$ git checkout v1.0.4
error: pathspec 'v1.0.4' did not match any file(s) known to git
```

**Comment by GoBig87** [comment]
and you did a `git pull` to update to the latest code from git?

I'm not sure why your git can't find it if you've already done a git pull and its all up to date.  You can manually copy the file contents here https://github.com/GoBig87/NordVpnLinuxGUI/blob/main/nord_vpn_api/nord_client.py and paste them into your `~/NordVpnLinuxGUI/nord_vpn_api/nord_client.py` file

**Comment by TinMan1325** [comment]
It's working now. Thank you

I went into /NordVpnLinuxGUI/NordVpnLinuxGUI and highlighted and copied everything, then went into /NordVpnLinuxGUI and pasted it there and it replaced everything
